In [7]:
import pandas as pd
from nettoyage import prepare_data
from sklearn.model_selection import train_test_split

In [ ]:
df_imputation, df_model = prepare_data() #df_imputation => tableau avec touté les colonnes, df_model => tableau avec que les variables numérisées

In [ ]:
pd.set_option("display.max_columns", None)
df_imputation.head()
df_model.head()

,SDGi,Life Expectancy,HDI,Per Capita GDP,Population (millions),Cropland_Footprint_Production,Grazing_Footprint_Production,Forest_Footprint_Production,Fish_Footprint_Production,BuiltUp_Footprint_Production,Carbon_Footprint_Production,Total_Footprint_Production,Cropland_Footprint_Consumption,Grazing_Footprint_Consumption,Forest_Footprint_Consumption,Fish_Footprint_Consumption,BuiltUp_Footprint_Consumption,Carbon_Footprint_Consumption,Total_Footprint_Consumption,Cropland,Grazing land,Forest land,Fishing ground,BuiltUp_Biocapacity,Total_Biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,Overshoot_Day_DOY,Income Group_LM,Income Group_UM,Income Group_HI,Quality Score_2B,Quality Score_2C,Quality Score_3A,Region_Asia-Pacific,Region_Central America/Caribbean,Region_EU,Region_Middle East/Central Asia,Region_North America,Region_Other Europe,Region_South America
0,53.9,64.486,0.509,564.617383,37.171898,0.139393,0.157740,0.052034,0.000084,0.028433,0.090303,0.467987,0.269788,0.165095,0.062879,0.001060,0.028433,0.155001,0.682255,0.139393,0.157740,0.014377,0.000000,0.028433,0.339943,-0.342312,0.431091,2.006970,NaN,0,0,0,0,0,1,0,0,0,1,0,0,0
1,71.0,78.458,0.792,5046.032611,2.882740,0.362065,0.195718,0.163174,0.018087,0.042248,0.639822,1.421114,0.547458,0.195848,0.207561,0.040595,0.042248,0.852748,1.886458,0.362065,0.195718,0.310590,0.082072,0.042248,0.992693,-0.893765,1.191981,1.900343,305.0,0,1,0,0,0,1,0,0,0,0,0,1,0
2,70.9,76.693,0.746,4759.830054,42.228398,0.249653,0.108329,0.079857,0.008417,0.037283,1.200642,1.684182,0.642917,0.150201,0.163528,0.013793,0.037283,1.333187,2.340909,0.249653,0.249356,0.025333,0.007541,0.037283,0.569166,-1.771742,1.479132,4.112872,245.0,0,1,0,0,0,1,0,0,0,0,0,0,0
3,50.3,60.782,0.582,3233.902767,30.809801,0.210919,0.054546,0.086584,0.078892,0.046437,0.201850,0.679229,0.329742,0.075853,0.089537,0.091383,0.046437,0.228893,0.861845,0.210919,0.918249,0.486000,0.175160,0.046437,1.836766,0.974922,0.544567,0.469218,NaN,1,0,0,0,0,1,0,0,0,0,0,0,0
4,NaN,76.885,0.772,15134.910090,0.096286,NaN,NaN,NaN,NaN,NaN,NaN,1.910373,NaN,NaN,NaN,NaN,NaN,NaN,4.655092,NaN,NaN,NaN,NaN,NaN,0.856509,-3.798584,2.941377,5.434962,123.0,0,0,1,1,0,0,0,1,0,0,0,0,0

In [4]:
train_df, test_df = train_test_split(
    df_model,
    test_size=0.2,
    random_state=123
)

In [5]:
print("Train lignes:", len(train_df))
print("Test lignes:", len(test_df))

Train lignes: 147
Test lignes: 37

In [12]:
y_var = "Overshoot_Day_DOY"

In [13]:
terms_all = [
    'SDGi',
    'Life Expectancy',
    'HDI',
    'Per Capita GDP',
    'Population (millions)',

    'Cropland_Footprint_Production',
    'Grazing_Footprint_Production',
    'Forest_Footprint_Production',
    'Fish_Footprint_Production',
    'BuiltUp_Footprint_Production',
    'Carbon_Footprint_Production',

    'Cropland_Footprint_Consumption',
    'Grazing_Footprint_Consumption',
    'Forest_Footprint_Consumption',
    'Fish_Footprint_Consumption',
    'BuiltUp_Footprint_Consumption',
    'Carbon_Footprint_Consumption',

    'Cropland',
    'Grazing land',
    'Forest land',
    'Fishing ground',
    'BuiltUp_Biocapacity',

    'Ecological (Deficit) or Reserve',
    'Number of Earths required',
    'Number of Countries required',
    
    'Income Group_LM',
    'Income Group_UM',
    'Income Group_HI',

    'Quality Score_2B',
    'Quality Score_2C',
    'Quality Score_3A',

    'Region_Asia-Pacific',
    'Region_Central America/Caribbean',
    'Region_EU',
    'Region_Middle East/Central Asia',
    'Region_North America',
    'Region_Other Europe',
    'Region_South America'
]

In [18]:
import statsmodels.api as sm
# 'cc' = cas complet donc le train pour les X complet sans NA 
train_cc = train_df.dropna()

y = train_cc[y_var]

In [19]:
train_cc.head()

,SDGi,Life Expectancy,HDI,Per Capita GDP,Population (millions),Cropland_Footprint_Production,Grazing_Footprint_Production,Forest_Footprint_Production,Fish_Footprint_Production,BuiltUp_Footprint_Production,Carbon_Footprint_Production,Total_Footprint_Production,Cropland_Footprint_Consumption,Grazing_Footprint_Consumption,Forest_Footprint_Consumption,Fish_Footprint_Consumption,BuiltUp_Footprint_Consumption,Carbon_Footprint_Consumption,Total_Footprint_Consumption,Cropland,Grazing land,Forest land,Fishing ground,BuiltUp_Biocapacity,Total_Biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required,Overshoot_Day_DOY,Income Group_LM,Income Group_UM,Income Group_HI,Quality Score_2B,Quality Score_2C,Quality Score_3A,Region_Asia-Pacific,Region_Central America/Caribbean,Region_EU,Region_Middle East/Central Asia,Region_North America,Region_Other Europe,Region_South America
157,67.0,71.5700,0.734,8100.331740,0.57599,0.347700,0.024808,1.362405,0.356750,0.093805,1.355462,3.540931,0.322578,0.001944,0.741389,0.248663,0.093805,1.656188,3.064567,0.347700,0.024808,73.039185,6.868026,0.093805,80.373525,77.308958,1.936384,0.038129,187.0,0,1,0,0,0,1,0,0,0,0,0,0,1
110,63.8,69.6890,0.735,4210.843450,3.17022,0.167473,5.442318,0.106842,0.000012,0.024100,2.318098,8.058844,0.333849,4.441324,0.149289,0.003768,0.024100,2.323385,7.275716,0.167473,7.221815,6.650153,0.078883,0.024100,14.142425,6.866709,4.597249,0.514460,78.0,1,0,0,0,0,1,1,0,0,0,0,0,0
85,79.8,84.2110,0.917,48505.526643,127.20200,0.084842,0.000031,0.144963,0.164612,0.060490,3.110110,3.565049,0.439604,0.122230,0.226046,0.259039,0.060490,3.500283,4.607692,0.084842,0.007452,0.339437,0.099872,0.060490,0.592093,-4.015599,2.911426,7.782037,124.0,0,0,1,0,0,1,1,0,0,0,0,0,0
148,81.6,81.3781,0.912,26709.658902,2.07784,0.247438,0.060314,1.512543,0.001228,0.082507,2.374753,4.278784,0.619900,0.192605,1.119268,0.049341,0.082507,3.302579,5.366201,0.247438,0.060314,1.804859,0.004314,0.082507,2.199432,-3.166769,3.390699,2.439813,106.0,0,0,1,0,0,1,0,0,1,0,0,0,0
8,82.1,81.6927,0.921,49711.014529,8.89139,0.519069,0.144925,1.311085,0.000060,0.131241,2.513096,4.619475,0.751800,0.269214,0.919378,0.056384,0.131241,3.936441,6.064460,0.519069,0.144925,1.877496,0.002956,0.131241,2.675686,-3.388774,3.831902,2.266506,94.0,0,0,1,0,0,1,0,0,1,0,0,0,0

In [20]:
valid_terms = [
    c for c in terms_all
    if train_cc[c].nunique() > 1
]

In [17]:
X = train_cc[valid_terms]

In [22]:
assert X.isna().sum().sum() == 0

In [23]:
# stepwise regression

def backward_stepwise_aic(X, y):
    X = sm.add_constant(X)
    remaining = list(X.columns)
    current_aic = sm.OLS(y, X[remaining]).fit().aic

    while True:
        aic_candidates = []
        
        for var in remaining:
            if var == "const":
                continue
            trial_vars = [v for v in remaining if v != var]
            model = sm.OLS(y, X[trial_vars]).fit()
            aic_candidates.append((model.aic, var, model, trial_vars))
        
        best_aic, worst_var, best_model, best_vars = min(aic_candidates, key=lambda x: x[0])
        
        if best_aic < current_aic:
            remaining = best_vars
            current_aic = best_aic
            final_model = best_model
        else:
            break

    return final_model, remaining


step_model, selected_vars = backward_stepwise_aic(X, y)

In [28]:
print("Variables sélectionnées :")
print(selected_vars)

print(step_model.summary())

# on compte les modalités des variables catégorielles sélectionnées pour voir si on peut les garder ou pas
print(train_cc["Quality Score_2B"].value_counts())
print(train_cc["Quality Score_2C"].value_counts())

Variables sélectionnées :
['const', 'Life Expectancy', 'HDI', 'Per Capita GDP', 'Population (millions)', 'Cropland_Footprint_Production', 'BuiltUp_Footprint_Production', 'Cropland_Footprint_Consumption', 'Forest_Footprint_Consumption', 'Fish_Footprint_Consumption', 'BuiltUp_Footprint_Consumption', 'Cropland', 'Grazing land', 'Forest land', 'Fishing ground', 'BuiltUp_Biocapacity', 'Ecological (Deficit) or Reserve', 'Number of Earths required', 'Income Group_LM', 'Income Group_UM', 'Income Group_HI', 'Quality Score_3A', 'Region_EU', 'Region_Middle East/Central Asia']
                            OLS Regression Results
==============================================================================
Dep. Variable:      Overshoot_Day_DOY   R-squared:                       0.917
Model:                            OLS   Adj. R-squared:                  0.890
Method:                 Least Squares   F-statistic:                     34.13
Date:                Tue, 10 Feb 2026   Prob (F-statistic):           6.65e-25
Time:                        11:29:03   Log-Likelihood:                -370.60
No. Observations:                  79   AIC:                             781.2
Df Residuals:                      59   BIC:                             828.6
Df Model:                          19
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                             400.9208     73.757      5.436      0.000     253.333     548.508
Life Expectancy                     4.5265      1.521      2.977      0.004       1.484       7.569
HDI                              -429.2735    119.544     -3.591      0.001    -668.480    -190.067
Per Capita GDP                      0.0009      0.000      2.257      0.028     9.8e-05       0.002
Population (millions)              -0.0401      0.022     -1.825      0.073      -0.084       0.004
Cropland_Footprint_Production      10.7453      5.928      1.813      0.075      -1.116      22.607
BuiltUp_Footprint_Production      -70.3907     30.999     -2.271      0.027    -132.419      -8.362
Cropland_Footprint_Consumption   -113.1564     28.650     -3.950      0.000    -170.485     -55.828
Forest_Footprint_Consumption      -19.4768      8.647     -2.252      0.028     -36.780      -2.174
Fish_Footprint_Consumption        -15.2264      7.001     -2.175      0.034     -29.234      -1.218
BuiltUp_Footprint_Consumption     -70.3907     30.999     -2.271      0.027    -132.419      -8.362
Cropland                           10.7453      5.928      1.813      0.075      -1.116      22.607
Grazing land                      -12.1161      5.146     -2.355      0.022     -22.413      -1.819
Forest land                         1.0774      4.920      0.219      0.827      -8.768      10.923
Fishing ground                      9.3791      6.331      1.481      0.144      -3.290      22.048
BuiltUp_Biocapacity               -70.3907     30.999     -2.271      0.027    -132.419      -8.362
Ecological (Deficit) or Reserve    -2.2749      4.671     -0.487      0.628     -11.622       7.072
Number of Earths required         -37.2988      7.633     -4.887      0.000     -52.572     -22.026
Income Group_LM                   -46.6327     26.552     -1.756      0.084     -99.764       6.499
Income Group_UM                   -69.5019     30.576     -2.273      0.027    -130.684      -8.320
Income Group_HI                  -106.7924     37.395     -2.856      0.006    -181.619     -31.966
Quality Score_3A                   16.9024     12.991      1.301      0.198      -9.092      42.897
Region_EU                          20.2028     14.488      1.394      0.168      -8.788      49.193
Region_Middle East/Central Asia    19.8409     12.546      1.581      0.119      -5.264      44.946
==============================================================================
Omnibus:                        3.514   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.173   Jarque-Bera (JB):                3.459
Skew:                           0.497   Prob(JB):                        0.177
Kurtosis:                       2.750   Cond. No.                     6.42e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.47e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
Quality Score_2B
0    79
Name: count, dtype: int64
Quality Score_2C
0    79
Name: count, dtype: int64

In [29]:
import pickle

with open("step_model.pkl", "wb") as f:
    pickle.dump(step_model, f)

# (optionnel mais très utile)
with open("selected_vars.pkl", "wb") as f:
    pickle.dump(selected_vars, f)